language: csharp
solution: cfuFor/cfuFor.sln

env:
  global:
    - CODECOV_TOKEN=:XtftekJqkM 

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
install:
  - sudo apt-get install mono-devel nunit-console
  - sudo apt-get install codecov
  - nuget restore cfuFor/cfuFor.sln  
  
script: 
  - xbuild cfuFor/cfuFor.sln
  - codecov

