language: csharp
solution: cfuFor/cfuFor.sln

env:
  global:
    - CODECOV_TOKEN=:XtftekJqkM 
  
install:
  - sudo apt-get install mono-devel nunit-console  
  - nuget restore cfuFor/cfuFor.sln  
  
script: 
  - xbuild cfuFor/cfuFor.sln
